LICENSE.txt
README.md
query_plan.go
statement.go
statement_test.go

This is an experimental implementation for showing Query Execution Plan (`EXPLAIN`).
```
spanner> EXPLAIN SELECT a.AlbumTitle, s.SongName FROM Albums AS a HASH JOIN Songs AS s ON a.SingerId = s.SingerId AND a.AlbumId = s.AlbumId\G
*************************** 1. row ***************************
Query_Execution_Plan (EXPERIMENTAL): 
.
└── Distributed Union (subquery_cluster_node: 1)
└── Serialize Result 
└── Hash Join (join_type: INNER)
├── Distributed Union (subquery_cluster_node: 4, call_type: Local)
│   └── Scan (Full scan: true, scan_target: Albums, scan_type: TableScan)
└── Distributed Union (subquery_cluster_node: 9, call_type: Local)
└── Scan (Full scan: true, scan_target: SongsBySingerAlbumSongNameDesc, scan_type: IndexScan)
1 rows in set (0.37 sec)
```

Query Execution Plan (EXPERIMENTAL)

---

README.md
decoder.go
decoder_test.go

Fixed nullable array always show an empty array string.
Before:
```
> select ArrayNullCol from t1;
+--------------+
| ArrayNullCol |
+--------------+
| []           |
| []           |
| [1, 2, 3]    |
+--------------+
```
After:
```
> select ArrayNullCol from t1;
+--------------+
| ArrayNullCol |
+--------------+
| NULL         | # This is actually NULL
| []           | # This is an empty array
| [1, 2, 3]    |
+--------------+
```
Also minor updated README.

Fix nullable array shows an empty array

---

README.md
main.go

Implement `--file`(`-f`) option.
```
$ spanner-cli -f schema.sql
```
Already `spanner-cli` can read SQL statements from a file in the following ways:
```
$ spanner-cli -e "$(cat schema.sql)"
$ cat schema.sql | spanner-cli
$ spanner-cli < schema.sql"
```
but the dedicated `--file`(`-f`) option is more intuitive for some users. It can be described in `--help`!

Implement --file option

---

cli.go
cli_test.go
main.go
session.go
statement.go

Add `--verbose` flag to display read/commit timestamps.
It display timestamps on:
* `BEGIN RO`
* It needs to emit `SELECT 1` so it changes behavior. Should revert it?
* discussion https://twitter.com/_NANASI880/status/1244566302221422593
* Although `google-cloud-go` defer `BeginTransaction` until `Query*()` is called, It makes sense `BEGIN RO` ensures to call `BeginTransaction` RPC.
* discussion https://twitter.com/furuyamayuki/status/1244861239273984000
* `COMMIT`
* `SELECT` in read only or single
* DML in implicit transaction
ref #28

Add verbose

---

integration_test.go

This issue has happened after merging https://github.com/cloudspannerecosystem/spanner-cli/pull/30.
<details><summary>Failed log: </summary>
<pre><code>
#!/bin/bash -eo pipefail
make test
=== RUN   TestSeparateInput
--- PASS: TestSeparateInput (0.00s)
=== RUN   TestBuildDdlStatements
--- PASS: TestBuildDdlStatements (0.00s)
=== RUN   TestPrintResult
=== RUN   TestPrintResult/DisplayModeTable
=== RUN   TestPrintResult/DisplayModeVertical
=== RUN   TestPrintResult/DisplayModeTab
--- PASS: TestPrintResult (0.00s)
--- PASS: TestPrintResult/DisplayModeTable (0.00s)
--- PASS: TestPrintResult/DisplayModeVertical (0.00s)
--- PASS: TestPrintResult/DisplayModeTab (0.00s)
=== RUN   TestDecodeColumn
=== RUN   TestDecodeColumn/bool
=== RUN   TestDecodeColumn/bytes
=== RUN   TestDecodeColumn/float64 …

Fix integration test

---

cli.go
cli_test.go
separator.go
separator_test.go
statement.go

Reimplemented statement separator to fix https://github.com/cloudspannerecosystem/spanner-cli/issues/33.
Note: Logic for parsing a statement is mostly taken from [spansql](https://github.com/googleapis/google-cloud-go/blob/master/spanner/spansql/parser.go).
close https://github.com/cloudspannerecosystem/spanner-cli/issues/33

Statement separator

---

cli.go
cli_test.go
statement.go

Enhance DDL batching to support arbitrary consecutive DDL statements. 
```sql:test.sql
CREATE TABLE test1(pk INT64) PRIMARY KEY(pk);
CREATE TABLE test2(pk INT64) PRIMARY KEY(pk);
INSERT INTO test1(pk) VALUES(1);
DROP TABLE test1;
DROP TABLE test2;
```
```
$ spanner-cli -p gcpug-public-spanner -i merpay-sponsored-instance -d apstndb -f test.sql
$ gcloud spanner operations list --project=gcpug-public-spanner --instance=merpay-sponsored-instance --database=apstndb
OPERATION_ID               STATEMENTS                         DONE  @TYPE
_auto_op_a4417d436908cfd9  DROP TABLE test1                   True  UpdateDatabaseDdlMetadata
DROP TABLE test2
_auto_op_98bd1b7db113ea43  CREATE TABLE test1 (               True  UpdateDatabaseDdlMetadata
pk INT64,
) PRIMARY KEY(pk)
CREATE TABLE test2 (
pk …
```

Enhanced ddl batching

---

README.md
cli.go
statement.go
statement_test.go

Implemented `DROP DATABASE database_name` statement.
1. Dropping database would be a dangerous operation in most of situations, so we show prompt to user to ask if we can proceed the execution.
2. Restrict users from dropping current session's database. This restriction will be eased in the future if we change current session implementation to decouple from the database.
```
spanner> DROP DATABASE test1;
Database "test1" will be dropped.
Do you want to continue? [yes/no] yes
Query OK, 0 rows affected (1.34 sec)
spanner>
```

DROP DATABASE statement

---

README.md
cli.go
cli_test.go
integration_test.go
statement.go

I chose following fields for display.
- elapsed (Total elapsed time)
- cpu (CPU time)
- scanned (Rows scanned)
- optimizer (Optimizer version)
These fields are equivalent to the output for `gcloud spanner databases execute-sql --query-mode=PROFILE`.
Query:
```
spanner> select * from t1;
+------+
| T1Id |
+------+
| 1    |
| 2    |
| 3    |
| 4    |
| 5    |
+------+
5 rows in set (2.69 msecs)
timestamp: 2020-04-19T13:11:03.496776+09:00
cpu:       1.11 msecs
scanned:   5 rows
optimizer: 2
```
Mutation:
```
spanner> insert into t1 (T1Id) values (6), (7), (8);
Query OK, 3 rows affected (5.42 sec)
timestamp: 2020-04-19T13:31:08.064703+09:00
```
Following statements used `SelectStatement` to execute query for INFORMATION SCHEMA, but it was not an ideal way since it uses user's transaction …

Show query stats in verbose mode

---

integration_test.go
statement.go
statement_test.go

Support quoted identifier and case-insensitive in `SHOW COLUMNS`, `SHOW INDEX`, `SHOW CREATE TABLE` statement.
It also changes:
* ~~Begin to use named capture groups because pattern become more complicated~~
* Add integration test of `SHOW COLUMNS`
* `integration_test.go` uses ADC when `SPANNER_CLI_INTEGRATION_TEST_CREDENTIAL` is not specified
* Talked in https://github.com/cloudspannerecosystem/spanner-cli/pull/32#pullrequestreview-384552221
refs #48

Fix to support case insensitiveness in SHOW * statement

---

main.go

Support use `.spanner_cli.cnf` file on current dir if exists.
Also fixed use `filepath.Join` instead of `path.Join`.

support use .spanner_cli.cnf file on current dir if exists

---

.circleci/config.yml
README.md

Add description of how to run integration tests with Cloud Spanner Emulator in local.
Additionally,
* Update `circleci/golang` image for:
* Improve `go mod download` speed by GOPROXY
* before [1m](https://app.circleci.com/pipelines/github/cloudspannerecosystem/spanner-cli/159/workflows/54998da1-2176-4b3e-ab2d-6c15b5b7b1fe/jobs/162/steps), after [4s](https://app.circleci.com/jobs/github/cloudspannerecosystem/spanner-cli/163) w/o caches
* Simplify `.circleci/config.yml` because Go module-mode is now default

Improve local integration tests

---

statement.go
statement_test.go

Without unquoting, quote ("`") is handled as a part of database name.
```
spanner> use `test`;
ERROR: ERROR: Unknown database "`test`"
```

Unquote database name for USE statement

---

README.md
main.go

Hi, thank you for your awesome project!
This PR sets `-p -i -d` with environment variables as well as flags. I think, for many people setting those flags every single operation is painful and easy to make mistakes.
I picked env names below since many toolchains in spanner-ecosystems something like `handy-spanner` and `wrench` already adopt those names. If `spanner-cli` adopt them, I think it would be comfortable.
```
SPANNER_PROJECT_ID
SPANNER_INSTANCE_ID
SPANNER_DATABASE_ID
```

setting `-p -i -d` with environment variables.

---

integration_test.go
statement.go

The SQL query for `SHOW INDEXES` didn't have table alias (`C`) and failed to be executed.

Fix SHOW INDEXES not working

---

query_plan.go

Display child type in `EXPLAIN` statements.
The followings are examples of query plans for queries in [Query execution operators](https://cloud.google.com/spanner/docs/query-execution-operators?hl=en) document.
```
Query_Execution_Plan (EXPERIMENTAL)
.
└── Distributed Union (subquery_cluster_node: 1)
└── Distributed Cross Apply (subquery_cluster_node: 9)
├── [Input]  Create Batch 
│   └── Distributed Union (call_type: Local, subquery_cluster_node: 4)
│       └── Compute Struct 
│           └── Scan (scan_type: IndexScan, scan_target: SongsBySingerAlbumSongNameDesc, Full scan: true)
└── [Map]  Serialize Result 
└── Cross Apply 
├── [Input]  Scan (scan_target: $v2, scan_type: BatchScan)
└── [Map]  Distributed Union (subquery_cluster_node: 14, call_type: Local)
└── FilterScan 
└── Scan …
```

Display child type in EXPLAIN statements

---

query_plan.go

This PR makes `treeprint` not to use ambiguous width characters.
```
+---------------------------------------------------------------------------------------------------+
| Query_Execution_Plan (EXPERIMENTAL)                                                               |
+---------------------------------------------------------------------------------------------------+
|                                                                                                   |
| .                                                                                                 |
| +- Distributed Union (subquery_cluster_node: 1)                                                   |
|     +- Distributed Cross Apply (subquery_cluster_node: 15)                                        |
|         +- …
```

Fix broken border when LC_CTYPE is CJK

---

go.mod
query_plan.go
query_plan_test.go

* Combine `scan_type` and `scan_target`
* Combine `call_type`, `iterator_type`, `scan_type` into node title
* Hide `subquery_cluster_node` because `spanner-cli` doesn't display node id
Discussed in https://github.com/cloudspannerecosystem/spanner-cli/issues/57#issuecomment-634399999
```sql
EXPLAIN SELECT * FROM Songs@{FORCE_INDEX=SongsBySongName}
```
```
Query_Execution_Plan (EXPERIMENTAL)
.
+- Distributed Union (subquery_cluster_node: 1)
+- Distributed Cross Apply (subquery_cluster_node: 15)
+- [Input]  Create Batch 
|   +- Distributed Union (subquery_cluster_node: 4, call_type: Local)
|       +- Compute Struct 
|           +- Scan (scan_type: IndexScan, scan_target: SongsBySongName, Full scan: true)
+- [Map]  Serialize Result 
+- Cross Apply 
+- [Input]  Scan (scan_type: BatchScan, …
```

Combine metadata fields

---

statement.go
statement_test.go

Fixed `SHOW CREATE TABLE` matches prefix of the table name.
Also fixed spanner-cli panics when user passes the table name which has invalid regular expression.
```
spanner> show tables;
+-----------------------------+
| Tables_in_execution_plan_01 |
+-----------------------------+
| Albums                      |
| Concerts                    |
| Singers                     |
| Songs                       |
+-----------------------------+
4 rows in set (0.28 sec)
spanner> show create table Son;
+-------+-------------------------------------------------+
| Table | Create Table                                    |
+-------+-------------------------------------------------+
| Son   | CREATE TABLE Songs (                            |
|       |   SingerId INT64 NOT NULL,                      | …
```

Fix show create table matches prefix of the table name

---

query_plan.go

I found `EXPLAIN` statement shows extra new lines like this:
```
spanner> explain select 1;             
+-------------------------------------+
| Query_Execution_Plan (EXPERIMENTAL) |
+-------------------------------------+                                                                                                    
|                                     |                 
| .                                   |
| +- Serialize Result                 |
|     +- Unit Relation                |
|                                     |
+-------------------------------------+
1 rows in set (0.34 sec)
```
I don't remember why I appended new line for the result, but anyway now I removed those new lines so it can align with the result of `EXPLAIN ANALYZE` statement.
```
spanner> explain …
```

Remove extra new lines for result of EXPLAIN statement

---

cli.go
query_plan.go
query_plan_test.go
statement.go

This PR implements showing predicates in `EXPLAIN ANALYZE` and `EXPLAIN`.
```sql
EXPLAIN ANALYZE
SELECT * FROM (
SELECT c.*
FROM UNNEST(GENERATE_ARRAY(0, 9)) AS OneShardCreatedAt,
UNNEST(ARRAY(
SELECT AS STRUCT OrderId, CreatedAt
FROM Order1M@{FORCE_INDEX=Order1MShardCreatedAtDesc}
WHERE ShardCreatedAt = OneShardCreatedAt
ORDER BY CreatedAt DESC LIMIT 10
)) AS c
ORDER BY c.CreatedAt DESC
LIMIT 10
)
INNER JOIN Order1M USING(OrderId)
```
```
+-----+----------------------------------------------------------------------------------------------+
| ID  | Query_Execution_Plan (EXPERIMENTAL)                                                          |
+-----+----------------------------------------------------------------------------------------------+
|     | . …
```

Show predicates in EXPLAIN / EXPLAIN ANALYZE

---

query_plan.go
query_plan_test.go
statement.go

ID of the root line shows `0` but it is wrong.
```
$ spanner-cli -e "EXPLAIN SELECT 1" -t
+----+-------------------------------------+
| ID | Query_Execution_Plan (EXPERIMENTAL) |
+----+-------------------------------------+
|  0 | .                                   |
|  0 | +- Serialize Result                 |
|  1 |     +- Unit Relation                |
+----+-------------------------------------+
```
Expected result is
```
$ spanner-cli -e "EXPLAIN SELECT 1" -t
+----+-------------------------------------+
| ID | Query_Execution_Plan (EXPERIMENTAL) |
+----+-------------------------------------+
|    | .                                   |
|  0 | +- Serialize Result                 |
|  1 |     +- Unit Relation                |
+----+-------------------------------------+
```
(It can …

Fix to make ID of root line empty in EXPLAIN and EXPLAIN ANALYZE

---

query_plan.go

This PR hide `Array Constructor` to achieve better consistency.
Currently, `Array Constructor` operator is shown as tree node.
```
$ spanner-cli -e "EXPLAIN SELECT a, b FROM UNNEST([1,2,3]) a WITH OFFSET b;" -t
+----+-------------------------------------+
| ID | Query_Execution_Plan (EXPERIMENTAL) |
+----+-------------------------------------+
|    | .                                   |
|  0 | +- Serialize Result                 |
|  1 |     +- Array Unnest                 |
|  2 |         +- Array Constructor        |
+----+-------------------------------------+
```
but it is a non-subquery scalar operator and it is usually hidden in visualization.
For examples, the document of same query in [Array unnest of Query execution operators](https://cloud.google.com/spanner/docs/query-execution …

Hide Array Constructor operator

---

go.mod
go.sum
query_plan.go
query_plan_test.go

`protobuf-go` v1.25 add native support of well-known types.
It simplify usages of `structpb`.
* `structpb.Struct` supports `MarshalJSON` to implement `json.Marshaller`
* `pbStruct` wrapper is not needed anymore
* `structpb.NewStruct` simplifies constructing `structpb.Struct`
* It make test cases simple and Go native

Simplify use of structpb using protobuf-go v1.25

---

statement.go

The padding of `ID` column in `EXPLAIN` is broken since #73 
Fix it.
```
+-----+----------------------------------------------------------------------------------------------+
| ID  | Query_Execution_Plan (EXPERIMENTAL)                                                          |
+-----+----------------------------------------------------------------------------------------------+
|     | .                                                                                            |
|   0 | +- Global Limit                                                                              |
| *1  |     +- Distributed Cross Apply                                                               |
|   2 |         +- [Input] Create Batch                                                              |
|   3 …
```

Fix layout of EXPLAIN

---

query_plan.go
query_plan_test.go
statement.go

It is not guaranteed that `*pb.QueryPlan.GetPlanNodes()` returns the PlanNode in ascending order, so we need to compare the planNode.Index to get the max id.
Otherwise the ID column shows invalid spaces like this,
```
+------+
| ID   |
+------+
|  *7  |
| *79  |
|   80 |
...
```

Fix maxVisibleNodeID could be random result

---

go.mod
go.sum
query_plan.go
query_plan_test.go
statement.go

Current query plan shows a dummy root row (`.`) which is rendered by treeprint. This root row is not needed and it's better to treat the first query execution operator as a root row.
This Pull Request has also the following changes.
* Remove `QueryPlanRow.TextOnly` field as the dummy root is removed
* Handle error properly which could happen in building the query execution plan tree.
```
$ spanner-cli -e 'EXPLAIN ANALYZE SELECT s.SongName, s.Duration FROM Songs@{force_index=SongsBySongName} AS s WHERE STARTS_WITH(s.SongName, "B");' -t
+-----+----------------------------------------------------------------+---------------+------------+---------------+                                                                      
| ID  | Query_Execution_Plan …
```

Remove dummy root for query execution plan

---

query_plan.go
query_plan_test.go

I changed the query plan indent size from 3 (default of treeprint) to 2. This is due to the following reasons.
* It looks better to align the branch character (`+`) with the first character of the operator name in the previous level.
* It shortens the width of the result, yet it is still readable.
```
$ spanner-cli -e 'EXPLAIN ANALYZE SELECT s.SongName, s.Duration FROM Songs@{force_index=SongsBySongName} AS s WHERE STARTS_WITH(s.SongName, "B");' -t
+-----+----------------------------------------------------------------+---------------+------------+---------------+                                                                      
| ID  | Query_Execution_Plan                                           | Rows_Returned | Executions | Total_Latency | …
```

Change query plan indent size

---

cli.go

close https://github.com/cloudspannerecosystem/spanner-cli/issues/80.
```
$ spanner-cli -p test -i test -d test -e "UPDATE Singers SET FirstName = 'Catalina2' WHERE SingerId = 2;"
$ spanner-cli -p test -i test -d test -e "UPDATE Singers SET FirstName = 'Catalina2' WHERE SingerId = 2;" -v
Query OK, 1 rows affected ()
timestamp: 2020-08-07T14:52:59.522765+09:00
```
```
$ spanner-cli -p test -i test -d test -e "SELECT * FROM Singers LIMIT 3;" 
SingerId        FirstName       LastName        SingerInfo      BirthDate
4       Lea     Martin  NULL    1991-11-09
2       Catalina2       Smith   NULL    1990-08-17
1       Marc    Richards        NULL    1970-09-03
$ spanner-cli -p test -i test -d test -e "SELECT * FROM Singers LIMIT 3;" -v
SingerId        FirstName       LastName        SingerInfo …
```

Always show result line with -v option even in batch mode

---

query_plan.go

The operator node named `Parameter` is shown but it is better to be hidden like `Function` and `Reference` etc.
```
> EXPLAIN SELECT * FROM Singers WHERE SingerId = @singer_id;
+-----+----------------------------------------------------+
| ID  | Query_Execution_Plan (EXPERIMENTAL)                |
+-----+----------------------------------------------------+
|  *0 | Distributed Union                                  |
|   1 | +- Local Distributed Union                         |
|   2 |    +- Serialize Result                             |
|  *3 |       +- FilterScan                                |
|   4 |       |  +- Table Scan (Table: Singers)            |
|  14 |       +- Parameter (name: singer_id, type: scalar) |
+-----+----------------------------------------------------+ …
```

Hide Parameter node

---

query_plan.go
query_plan_test.go
statement.go
testdata/plans/hash_join.input.json

I didn't care about Condition predicate of Hash Join in #87 but it is already shown.
```
+----+---------------------------------------------------------------------------------+
| ID | Query_Execution_Plan (EXPERIMENTAL)                                             |
+----+---------------------------------------------------------------------------------+
|  0 | Distributed Union                                                               |
|  1 | +- Serialize Result                                                             |
| *2 |    +- Hash Join (join_type: INNER)                                              |
|  3 |       +- [Build] Local Distributed Union                                        |
|  4 |       |  +- Table Scan (Full scan: true, Table: Albums) …
```

Add Condition of Hash Join as a supported predicate

---

query_plan.go
query_plan_test.go
testdata/plans/array_subqueries.input.json
testdata/plans/scalar_subqueries.input.json

This PR fixes the bug which shows duplicated subtrees when the plan have scalar subqueries.
```sql
SELECT a.AlbumId,
ARRAY(SELECT ConcertDate
FROM Concerts
WHERE Concerts.SingerId = a.SingerId)
FROM Albums AS a;
```
```
+-----+--------------------------------------------------------------------+
| ID  | Query_Execution_Plan (EXPERIMENTAL)                                |
+-----+--------------------------------------------------------------------+
|   0 | Distributed Union                                                  |
|   1 | +- Local Distributed Union                                         |
|   2 |    +- Serialize Result                                             |
|   3 |       +- Index Scan (Full scan: true, Index: AlbumsByAlbumTitle)   |
|   7 |       +- Array Subquery …
```

Suppress to show duplicated subtrees of scalar subqueries

---

go.mod
query_plan.go
query_plan_test.go
statement.go
testdata/plans/array_subqueries_with_compute_struct.input.json
testdata/plans/scalar_subquery_with_filter_scan.input.json

#90 fixes subquery handling in Serialize Result but Compute Struct also have subqueries with `Scalar` link type because they are similar operators.
https://cloud.google.com/spanner/docs/query-execution-operators?hl=en#serialize_result
>A serialize result operator is a special case of the compute struct operator
This PR fixes the bug and simplify `IsVisible` related logics:
* Relational operators is always rendered.
* Scalar operators isn't rendered except subquery operators.
* Subquery operators are appeared with `Scalar` typed child link from relational operators.
* (Subqueries are usually optimized, so subquery operators don't appear in other cases AFAIK.)
```sql
SELECT si.*,
ARRAY(SELECT AS STRUCT a.*,
ARRAY(SELECT AS STRUCT so.*
FROM Songs so
WHERE a.SingerId = so.SingerId AND …
```

Improve subquery handling

---

.circleci/config.yml
README.md
integration_test.go
statement.go
statement_test.go

I added `TRUNCATE TABLE <table>` statement which deletes all rows from the table.
This is useful when we want to preserve table itself but delete all rows without worrying about transaction's mutation limit. In other words, we can delete all records while preserving underlying splits.
More context: https://cloud.google.com/solutions/best-practices-cloud-spanner-gaming-database#pre-warm_the_database_before_launch

TRUNCATE TABLE statement

---

README.md
cli.go
integration_test.go
statement.go
statement_test.go

`PARTITIONED (UPDATE|DELETE) ...;`
```
spanner> select * from Songs;
+----------+---------+---------+-------------------------+----------+-----------+
| SingerId | AlbumId | TrackId | SongName                | Duration | SongGenre |
+----------+---------+---------+-------------------------+----------+-----------+
| 2        | 1       | 1       | Let's Get Back Together | 182      | COUNTRY   |
| 2        | 1       | 2       | Starting Again          | 156      | ROCK      |
| 2        | 1       | 3       | I Knew You Were Magic   | 294      | BLUES     |
| 2        | 1       | 4       | 42                      | 185      | CLASSICAL |
| 2        | 1       | 5       | Blue                    | 238      | BLUES     |
| 2        | 1       | 6       | Nothing Is The Same     | 303      | …
```

Add Partitioned DML

---

statement.go

This PR fixed a bug that the read-write transaction doesn't finish when the execution of SELECT statement returns `codes.Aborted`.
```
> BEGIN RW;
Query OK, 0 rows affected (0.01 sec)
(rw txn)> @{LOCK_SCANNED_RANGES=exclusive} SELECT * FROM tbl WHERE pk = 0;
Empty set (10.44 msecs)
(rw txn)> @{LOCK_SCANNED_RANGES=exclusive} SELECT * FROM tbl WHERE pk = 0;
ERROR: spanner: code = "Aborted", desc = "Transaction was aborted."
>  
```
This PR doesn't change the behavior of codes other than `codes.Aborted` so syntax error doesn't abort transaction. It seems user friendly.
```
(rw txn)> SELECT * FROM tbl WHERE pk = '';
ERROR: spanner: code = "InvalidArgument", desc = "No matching signature for operator = for argument types: INT64, STRING. Supported signature: ANY = ANY [at 1:25]\\nSELECT * FROM …
```

Finish read-write transaction when SELECT statement was aborted

---

cli.go
integration_test.go
session.go

I have found that Cloud Spanner has a mechanism to increase the lock priority of the session if a transaction on the session was aborted: https://cloud.google.com/spanner/docs/reference/rest/v1/TransactionOptions#retrying-aborted-transactions
This mechanism looks fine for real-world application to prevent the same transaction from being wounded multiple times, but in spanner-cli, it makes the result of subsequent transaction inconsistent. See #98 for example.
To make the result of the transaction consistent over subsequent transactions, I changed the CLI to recreate the Cloud Spanner's session if transaction is aborted.
close: #98

Recreate session if transaction is aborted

---

cli.go
session.go
statement.go

Transaction heartbeat is deferred to the time when a user executes a SQL statement on the transaction. This ensures that a user-initiated query is the first query after `BeginTransaction` is called. See https://github.com/cloudspannerecosystem/spanner-cli/issues/100 for more details.
This PR also contains the refactoring of transaction handling. I have moved the logic of transaction state from `statement.go` to `session.go` to handle the state in one place.
This is the actual RPCs called when I executed the following commands in spanner-cli.
```
BEGIN;
SELECT * FROM Accounts WHERE UserId = 1;
UPDATE Accounts SET Balance = 4000 WHERE UserId = 1;
COMMIT
```
(Note: order by timestamp DESC)
close: https://github.com/cloudspannerecosystem/spanner-cli/issues/100

Defer transaction heartbeat

---

cli.go
cli_test.go
statement.go

The `deleted_rows_scanned` in QueryStats is usuful for diagnosing bottlenecks in scanned tables with many insertion and deletion.   
I added `deleted rows scanned` section in verbose mode.
```
spanner> select count(*) from new_orders;
+--------+
|        |
+--------+
| 835790 |
+--------+
1 rows in set (70.49 msecs)
timestamp: 2021-03-09T14:04:10.376489+09:00
cpu:       325.3 msecs
scanned:   835790 rows
optimizer: 2
```
```
spanner> select count(*) from new_orders;
+--------+
|        |
+--------+
| 835790 |
+--------+
1 rows in set (70.49 msecs)
timestamp:            2021-03-09T14:04:10.376489+09:00
cpu time:             325.3 msecs
rows scanned:         835790 rows
deleted rows scanned: 232750 rows
optimizer version:    2
```

Show deleted_rows_scanned stats in verbose mode

---

README.md

It looks like escape (`\`) character is not needed.

Remove unused escape characters

---

session_test.go

This is a supplementary test for https://github.com/cloudspannerecosystem/spanner-cli/pull/110.
I used [spannertest](https://pkg.go.dev/cloud.google.com/go/spanner/spannertest) to capture gRPC requests and assert request priorities coming from spanner-cli.

Add test for request priority

---

statement.go
statement_test.go

This PR supports the following three [VIEW](https://cloud.google.com/spanner/docs/views) statements.
1. Create View: `CREATE VIEW ...;`
2. Update View: `CREATE OR REPLACE VIEW ...;`
3. Delete View: `DROP VIEW ...;`
Example:
```
spanner> CREATE TABLE Singers (
->   SingerId   INT64 NOT NULL,
->   FirstName  STRING(1024),
->   LastName   STRING(1024),
->   SingerInfo BYTES(MAX),
-> ) PRIMARY KEY (SingerId);
Query OK, 0 rows affected (4.16 sec)
spanner> INSERT INTO Singers (SingerId, FirstName, LastName) VALUES (1, "foo", "bar");
Query OK, 1 rows affected (0.58 sec)
spanner> CREATE VIEW SingerNames
-> SQL SECURITY INVOKER
-> AS SELECT
->   Singers.SingerId AS SingerId,
->   Singers.FirstName || " " || Singers.LastName AS Name
-> FROM Singers;
Query OK, 0 rows affected (4.42 sec)
spanner> …
```

Support VIEW statements

---

cli.go
cli_test.go
statement.go
statement_test.go

This PR has two changes to support [optimizer statistics](https://cloud.google.com/spanner/docs/query-optimizer/overview#query_optimizer_statistics_packages):
1. Support `ALTER STATISTICS` statement.
2. Show optimizer statistics package name in verbose mode.
Example:
```
spanner> ALTER STATISTICS auto_20210829_05_22_28UTC SET OPTIONS (allow_gc = false);
Query OK, 0 rows affected (40.93 sec)
spanner> SELECT * FROM Singers;
+----------+-----------+----------+------------+------------+
| SingerId | FirstName | LastName | SingerInfo | BirthDate  |
+----------+-----------+----------+------------+------------+
| 1        | b         | Richards | NULL       | 1970-09-03 |
| 2        | Catalina  | Smith    | NULL       | 1990-08-17 |
| 3        | Alice     | Trentor  | NULL       | 1991-10-02 |
| …
```

Support optimizer statistics

---

decoder.go
decoder_test.go

It seems that the BYTES type in Cloud Spanner needs to be encoded as base64 with padding.
https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/type.proto#L116-L118
https://github.com/googleapis/google-cloud-go/blob/7eaaa470fda5dc7cd1ff041d6a898e35fb54920e/spanner/value.go#L1085
Currently, spanner-cli uses base64.RawStdEncoding, but the padding is missing when outputting the data.
```console
$ spanner-cli -p <my-project> -i <my-instance> -d <my-db> -e 'SELECT id, bytes FROM TestTable'
id      bytes
1       aGVsbG8sIHdvcmxkIQ
```
```console
$ spanner-cli -p <my-project> -i <my-instance> -d <my-db> -e 'SELECT id, bytes FROM TestTable'
id      bytes
1       aGVsbG8sIHdvcmxkIQ==
```

Fix from base64.RawStdEncoding to base64.StdEncoding

---

README.md

Some users ask how to use the Cloud Spanner Emulator, so it seems to be a good idea to include it.

Add "Using with the Cloud Spanner Emulator" to README.md

---

README.md
session.go
session_test.go
statement.go
statement_test.go

This PR adds Cloud Spanner's [transaction tags and request tags](https://cloud.google.com/spanner/docs/introspection/troubleshooting-with-tags) support to spanner-cli.
Transaction tags are tags set at the beginning of a transaction that makes the transaction identifiable. Request tags can be set for each request and identify individual requests.
According to [this document](https://cloud.google.com/spanner/docs/introspection/troubleshooting-with-tags#mapping_between_api_methods_and_requesttransaction_tag), read-write transaction supports transaction tags and request tags. Read-only transaction only supports request tags.
So, I implemented this feature as follows.
In a read-write transaction, you can add arbitrary tags following `BEGIN RW TAG <tags>`.
spanner-cli adds the tags set in …

Support Transaction Tags and Request Tags

---

README.md

There were some feedback that current installation process doesn't work for Go <1.16 users, so I updated the installation process depending on the version of Go.
close: https://github.com/cloudspannerecosystem/spanner-cli/issues/127

Update installations depending on the version of Go

---

statement.go

I hope `EXPLAIN SELECT ...` statement has been battle-tested and it's no more in experimental phase. Let's remove it.

Remove EXPERIMENTAL flag for query execution plan

---

cli.go
integration_test.go
session.go
session_test.go
statement.go

Currently spanner-cli doesn't handle `SIGINT`, so if it receives `SIGINT` in response to the `Ctrl-C`, the CLI is killed suddenly and inflight request is not canceled properly.
This PR handles the `SIGINT` properly for both interactive mode and batch mode. This PR also removes the `Session.ctx` field, which was not used effectively at this moment.
More background: #133
```
spanner> SELECT COUNT(*) FROM t1;
^CERROR: spanner: code = "Canceled", desc = "context canceled"
```
```
spanner-cli -p <PROJECT> -i <INSTANCE> -d <DATABASE> -e 'SELECT COUNT(*) FROM t1;'
^CERROR: spanner: code = "Canceled", desc = "context canceled
```

Handles SIGINT (Ctr-C) and gracefully stops an inflight request.

---

statement.go
statement_test.go

This PR adds the generic DDLs(`CREATE / ALTER / DROP`) support.
```
spanner> CREATE CHANGE STREAM EverythingStream FOR ALL;
Query OK, 0 rows affected (24.15 sec)
spanner> ALTER CHANGE STREAM EverythingStream DROP FOR ALL;
Query OK, 0 rows affected (7.07 sec)
spanner> DROP CHANGE STREAM EverythingStream;
Query OK, 0 rows affected (17.15 sec)
```
We can specialize the regex pattern and the statement like `CREATE DATABASE` and `DROP DATABASE` statements if needed.
fixes #135

Support generic DDLs

---

cli.go
main.go

Add `--history` option in order to make the history file path to be configurable.
- Currently, the history file path is fixed as `/tmp/spanner_cli_readline.tmp`. But, I'd like to make the file path to be configurable. 
- In my case, I'm using `docker compose` to run `spanner-cli` and would like to preserve the history file across the `docker compose run`. Thought I can mount the current `/tmp/spanner_cli_readline.tmp` into the container, I think making the history file path to be configurable is a more explicit and easy way to preserve the histories. (Other database client like `mysql` or `psql` also provide the way to change the history file path).

Make the history file path to be configurable

---

README.md
statement.go
statement_test.go

This PR adds fine-grained ACL related DDLs support(`GRANT`, `REVOKE`).
```
spanner> CREATE ROLE singers_reader;
Query OK, 0 rows affected (6.89 sec)
spanner> GRANT SELECT ON TABLE Singers TO ROLE singers_reader;
Query OK, 0 rows affected (6.49 sec)
spanner> REVOKE SELECT ON TABLE Singers FROM ROLE singers_reader;
Query OK, 0 rows affected (7.47 sec)
spanner> DROP ROLE singers_reader;
Query OK, 0 rows affected (6.52 sec)
```
close #139

Add fine-grained ACL support

---

session.go
session_test.go
statement.go

Support to show result sets of `DmlStatement`.
DMLs with `THEN RETURN`
```
spanner> INSERT t1(pk) VALUES(1),(2) THEN RETURN *;
+----+------+
| pk | col  |
+----+------+
| 1  | NULL |
| 2  | NULL |
+----+------+
Query OK, 2 rows affected (0.03 sec)
timestamp:      2023-03-24T16:31:01.252904+09:00
mutation_count: 2
spanner> UPDATE t1 SET col = pk WHERE TRUE THEN RETURN *;
+----+-----+
| pk | col |
+----+-----+
| 1  | 1   |
| 2  | 2   |
+----+-----+
Query OK, 2 rows affected (0.03 sec)
timestamp:      2023-03-24T16:31:07.653541+09:00
mutation_count: 4
spanner> DELETE t1 WHERE TRUE THEN RETURN *;
+----+-----+
| pk | col |
+----+-----+
| 1  | 1   |
| 2  | 2   |
+----+-----+
Query OK, 2 rows affected (0.04 sec)
timestamp:      2023-03-24T16:31:16.285057+09:00
mutation_count: 2
```
normal DMLs …

support THEN RETURN in DmlStatement

---

cli.go
cli_test.go

This PR fixes a bug introduced by #150.
Valid because of a comment after the last semicolon.
```
SELECT 1; /* comment */
```
Invalid because empty statements terminated by semicolons are not permitted.
```
SELECT 1; /* comment */; SELECT 2
```
fixes #153

Permit a comment after the last semicolon

---

statement.go
statement_test.go

From this release [^1], [Stored system procedures](https://cloud.google.com/spanner/docs/reference/standard-sql/stored-procedures) is supported.
As I tested at cloud console [^2], it runs as query.
So I changed statement.go to parse `CALL` to `SelectStatement` and it works.
Let me know if we need to parse `CALL` statement to another struct. 
<details><summary>Test Result (Click me)</summary>
- run heavy query
```
spanner> SELECT * FROM Users AS a CROSS JOIN Users AS b;
```
- select query_id and run stored system procedures
```
spanner> SELECT * FROM spanner_sys.oldest_active_queries;
+-----------------------------+----------------------+-------------------------------------------------+----------------+----------------------------------------------------------------+---------------------+ …
```

support stored system procedures

---

statement.go
statement_test.go

This PR adds `GRAPH`(and `EXPLAIN GRAPH`, `EXPLAIN ANALYZE GRAPH`) statement support into spanner-cli.
```
spanner> GRAPH FinGraph MATCH (n) RETURN LABELS(n) AS label, n.id;
+-----------+----+
| label     | id |
+-----------+----+
| [Account] | 7  |
| [Account] | 16 |
| [Account] | 20 |
| [Person]  | 1  |
| [Person]  | 2  |
| [Person]  | 3  |
+-----------+----+
6 rows in set (0.81 msecs)
spanner> EXPLAIN GRAPH FinGraph MATCH (n) RETURN LABELS(n) AS label, n.id;
+-----+----------------------------------------------------------------------------------------+
| ID  | Query_Execution_Plan                                                                   |
+-----+----------------------------------------------------------------------------------------+
|   0 | Serialize Result …
```

Support GRAPH statement

---

README.md
statement.go
statement_test.go

related #172
This PR adds support of FQN in the below statements.
```
spanner> SHOW CREATE TABLE Singers;
+---------+----------------------------+
| Table   | Create Table               |
+---------+----------------------------+
| Singers | CREATE TABLE Singers (     |
|         |   SingerId INT64 NOT NULL, |
|         |   FirstName STRING(1024),  |
|         |   LastName STRING(1024),   |
|         |   SingerInfo BYTES(MAX),   |
|         |   BirthDate DATE,          |
|         | ) PRIMARY KEY(SingerId)    |
+---------+----------------------------+
1 rows in set (2.26 sec)
spanner> SHOW CREATE TABLE sch1.Singers;
+--------------+-----------------------------+
| Table        | Create Table                |
+--------------+-----------------------------+
| sch1.Singers | CREATE TABLE …
```

Support FQN in statements

---

README.md
cli.go
main.go

The `--endpoint` flag (added by https://github.com/cloudspannerecosystem/spanner-cli/pull/162) allows spanner-cli to connects to a custom API endpoint.
However, gRPC will only send credentials (specified by `--credentials` or env `GOOGLE_APPLICATION_CREDENTIALS`) when TLS is enabled. To ease some use cases during local testing, this pull request adds `--skip-tls-verify` which implicitly enables TLS while skipping certificate verification.

Add CLI flag `--skip-tls-verify`

---

README.md
cli.go
go.mod
go.sum
integration_test.go
main.go
session.go
session_test.go
statement.go

This PR implements `--proto-descriptor-file` option with `USE` statement compatibility.
```
$ go run ./ --database apstndb-sampledb3 --proto-descriptor-file order_descriptors.pb
Connected.
spanner> ALTER PROTO BUNDLE INSERT (`examples.shipping.OrderHistory`);
Query OK, 0 rows affected (11.11 sec)
spanner> USE apstndb-sampledb-with-data-idx;
spanner> ALTER PROTO BUNDLE INSERT (`examples.shipping.OrderHistory`);
Query OK, 0 rows affected (9.23 sec)
```
fixes #174

Implement --proto-descriptor-file

---

cli_test.go
main.go
query_plan_test.go

SSIA
As you may know, `io/ioutil` package is deprecated now.
> Deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.
> https://pkg.go.dev/io/ioutil

replace `io/ioutil` with `io`, `os` package

---

README.md
main.go

Hello. Thank you for maintaining very useful cli for spanner!
SSIA
It is more useful for troubleshooting if spanner-cli can show its version.
I intentionally added `Version` to `spannerOptions`, though it might be not good idea to do so because it seems that `--version` is not a option to execute spanner-cli, but a kind of sub-command.
The reason why I did so is that I feel it is difficult to show description of `--version` if I don't add `Version` to `spannerOptions`.
As an alternative, I considered to parse `os.Args` like below. But as I mentioned above it it difficult to show description of `--version` when `spanner-cli --help` is executed.
```go
if len(os.Args) == 2 && os.Args[1] == "--version" {
fmt.Fprintf(os.Stdout, "%s\n", versionInfo())
os.Exit(0)
}
```
Please give me your …

Add cli flag `--version` to show version of spanner-cli

---

README.md
session.go
session_test.go
statement.go
statement_test.go

Enables optionally setting the isolation level at a transaction-level to either `SERIALIZABLE` or `REPEATABLE READ`. If the isolation level is not set, Spanner will default to `SERIALIZABLE` isolation.

Add transaction-level isolation level setting

---

Dockerfile

```sh
% docker build -t spanner-cli .
...
=> ERROR [build 4/5] RUN go mod download                                                                  0.1s
------
> [build 4/5] RUN go mod download:
0.123 go: go.mod requires go >= 1.24 (running go 1.23.11; GOTOOLCHAIN=local)
------
1 warning found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
Dockerfile:5
--------------------
3 |     WORKDIR /go/src/spanner-cli
4 |     COPY . .
5 | >>> RUN go mod download
6 |     RUN CGO_ENABLED=0 go build -o /go/bin/spanner-cli
7 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c go mod download" did not complete successfully: exit code: 1
```
```sh
% docker build -t spanner-cli .
...
=> exporting to image …
```

Upgrade Go in Dockerfile
